'use strict'
const { contextBridge, ipcRenderer, webFrame } = require('electron')

// BEGIN OFFICIAL BROWSER BRIDGE
// Generated by build/sync-official-browser.cjs; source and MIT license: vendor/deepseek-desktop.
const DESKTOP_IPC = {
  "shortcutsInput": "dsh-desktop:shortcuts-input",
  "shortcutsCloseWindow": "dsh-desktop:shortcuts-close-window",
  "shortcutsGet": "dsh-desktop:shortcuts-get",
  "shortcutsEdit": "dsh-desktop:shortcuts-edit",
  "shortcutsChanged": "dsh-desktop:shortcuts-changed",
  "shortcutsRecording": "dsh-desktop:shortcuts-recording",
  "browserAcquire": "dsh-desktop:browser-acquire",
  "browserRelease": "dsh-desktop:browser-release",
  "browserOpenRequested": "dsh-desktop:browser-open-requested"
}
function createDesktopBrowserBridge() {
    const listeners = new Map();
    ipcRenderer.on(DESKTOP_IPC.browserOpenRequested, (_event, request)=>{
        if (typeof request !== 'object' || request === null || !('lease' in request) || !('url' in request) || typeof request.lease !== 'string' || typeof request.url !== 'string') return;
        const callbacks = listeners.get(request.lease);
        if (callbacks === undefined) return;
        for (const callback of [
            ...callbacks
        ]){
            try {
                callback(request.url);
            } catch (error) {
                console.error('Desktop browser link handler failed', error);
            }
        }
    });
    return {
        acquire: (workspace)=>ipcRenderer.invoke(DESKTOP_IPC.browserAcquire, workspace),
        release: (lease)=>ipcRenderer.invoke(DESKTOP_IPC.browserRelease, lease),
        onOpenRequested (lease, listener) {
            let callbacks = listeners.get(lease);
            if (callbacks === undefined) {
                callbacks = new Set();
                listeners.set(lease, callbacks);
            }
            callbacks.add(listener);
            return ()=>{
                callbacks.delete(listener);
                if (callbacks.size === 0 && listeners.get(lease) === callbacks) listeners.delete(lease);
            };
        }
    };
}
function createDesktopBrowserApi() {
    return {
        protocolVersion: 1,
        browser: createDesktopBrowserBridge(),
        keyboard: {
            closeWindow: (revision)=>ipcRenderer.invoke(DESKTOP_IPC.shortcutsCloseWindow, revision),
            subscribe: (listener)=>{
                const handle = (_event, input)=>{
                    if (input.kind === 'iframe') {
                        const element = document.activeElement;
                        if (!(element instanceof HTMLIFrameElement) || !element.isConnected || !element.matches('iframe[data-sidebar-browser-frame], iframe[data-html-preview]')) return;
                        if (input.frameName === '' || element.name !== input.frameName) return;
                    }
                    if (input.kind === 'webview') {
                        const element = document.activeElement;
                        if (element?.matches('webview[data-sidebar-browser-frame]') !== true || !element.isConnected || input.frameName === '' || element.getAttribute('name') !== input.frameName) return;
                    }
                    listener(input);
                };
                ipcRenderer.on(DESKTOP_IPC.shortcutsInput, handle);
                return ()=>{
                    ipcRenderer.off(DESKTOP_IPC.shortcutsInput, handle);
                };
            }
        },
        shortcuts: {
            get: (definitions)=>ipcRenderer.invoke(DESKTOP_IPC.shortcutsGet, definitions),
            edit: (edit, revision)=>ipcRenderer.invoke(DESKTOP_IPC.shortcutsEdit, edit, revision),
            recording: (active)=>ipcRenderer.invoke(DESKTOP_IPC.shortcutsRecording, active),
            subscribe (listener) {
                const handle = (_event, snapshot)=>{
                    listener(snapshot);
                };
                ipcRenderer.on(DESKTOP_IPC.shortcutsChanged, handle);
                return ()=>{
                    ipcRenderer.off(DESKTOP_IPC.shortcutsChanged, handle);
                };
            }
        }
    };
}
// END OFFICIAL BROWSER BRIDGE

const initialState = ipcRenderer.sendSync('desktop:chrome-init')
if (initialState?.browser && !initialState.local && process.isMainFrame) {
  contextBridge.exposeInMainWorld('dshDesktop', createDesktopBrowserApi())
  const markPlatform = () => {
    if (!document.documentElement) return false
    document.documentElement.dataset.platform = initialState.platform
    return true
  }
  if (!markPlatform()) {
    const observer = new MutationObserver(() => { if (markPlatform()) observer.disconnect() })
    observer.observe(document, { childList: true, subtree: true })
  }
}
let currentLanguage = initialState?.language || 'zh'
if (initialState) contextBridge.exposeInMainWorld('desktopLocale', { get: () => currentLanguage })

// 配置 API 只存在于主进程验证过的配置中心本地页。
if (initialState?.purpose === 'settings' && initialState.local) contextBridge.exposeInMainWorld('pluginApi', {
  list: () => ipcRenderer.invoke('plugins:list'),
  run: (action, spec) => ipcRenderer.invoke('plugins:run', action, spec),
  installLocal: (kind) => ipcRenderer.invoke('plugins:installLocal', kind),
  restart: () => ipcRenderer.invoke('plugins:restart'),
  generalGet: () => ipcRenderer.invoke('general:get'),
  generalSave: (values) => ipcRenderer.invoke('general:save', values),
  proxyGet: () => ipcRenderer.invoke('proxy:get'),
  proxySave: (config) => ipcRenderer.invoke('proxy:save', config),
  proxyTest: (config, url) => ipcRenderer.invoke('proxy:test', config, url),
  proxyPickCa: () => ipcRenderer.invoke('proxy:pickCa'),
  serverRestart: () => ipcRenderer.invoke('server:restart'),
})

/** 标记上游支持的平台布局，并同步本地页与原生窗口配色。 */
function applyState(state) {
  const root = document.documentElement
  currentLanguage = state.language || 'zh'
  if (state.local && root.lang !== currentLanguage) {
    root.lang = currentLanguage
    window.dispatchEvent(new Event('desktop-language-change'))
  }
  const title = document.getElementById('desktop-titlebar')
  if (title) title.textContent = state.purpose === 'settings' ? (currentLanguage === 'en' ? 'Configuration center' : '配置中心') : state.platform === 'darwin' ? '' : 'DeepSeek Harness'
  // 布局标记独立于仅在已接入官方键盘桥的主界面启用的平台标记。
  root.dataset.desktopPlatform = state.platform
  root.toggleAttribute('data-fullscreen', state.fullscreen)
  root.toggleAttribute('data-desktop-local', state.local)
  root.toggleAttribute('data-desktop-dark', state.palette.dark)
  const zoom = webFrame.getZoomFactor()
  const height = state.platform === 'win32' ? Math.round(Math.max(40, 40 * zoom)) : state.platform === 'darwin' ? 48 : 0
  root.style.setProperty('--desktop-titlebar-height', `${height / zoom}px`)
  root.style.setProperty('--desktop-traffic-clearance', `${88 / zoom}px`)
  if (state.platform === 'win32' && !state.local) {
    root.setAttribute('data-windows-titlebar', '')
    root.style.setProperty('--dsh-windows-titlebar-height', `${height / zoom}px`)
  }
  for (const key of ['sidebar', 'content', 'text']) root.style.setProperty(`--desktop-${key}`, state.palette[key])
}

/** 标记 Web 侧栏的结构节点，窗口控制随侧栏宽度与折叠状态定位。 */
function watchMacLayout() {
  const root = document.documentElement
  let frame, sidebar, pending = false
  // 折叠入口独立于零宽侧栏，保留完整的原生鼠标命中区域。
  const leading = document.createElement('div')
  leading.id = 'desktop-leading'
  leading.hidden = true
  const controls = ['toggle', 'new-session'].map(action => {
    const button = document.createElement('button')
    button.type = 'button'
    button.setAttribute(`data-desktop-leading-${action}`, '')
    const selector = action === 'toggle' ? '[data-desktop-sidebar-toggle]' : '[data-desktop-new-session]'
    button.addEventListener('click', () => sidebar?.querySelector(selector)?.click())
    leading.append(button)
    return { button, selector, icon: '' }
  })
  document.body.append(leading)
  const resize = new ResizeObserver(() => schedule())
  const mark = (element, name) => { if (element && !element.hasAttribute(name)) element.setAttribute(name, '') }
  const update = () => {
    pending = false
    const next = document.querySelector('[data-shell-overlay]')?.parentElement
    if (!next || next.children[0]?.hasAttribute('data-shell-overlay')) { leading.hidden = true; return }
    if (next !== frame) {
      resize.disconnect()
      frame = next
      sidebar = frame.children[0]
      resize.observe(sidebar)
    }
    mark(frame, 'data-desktop-frame')
    mark(sidebar, 'data-desktop-sidebar')
    mark(frame.children[1], 'data-desktop-center')
    const row = sidebar.querySelector('[data-window-drag]')
    mark(row, 'data-desktop-logo-row')
    mark(row?.parentElement, 'data-desktop-sidebar-root')
    const buttons = row?.querySelectorAll('button[aria-label]')
    mark(buttons?.[buttons.length - 1], 'data-desktop-sidebar-toggle')
    mark(row?.parentElement.querySelector(':scope > button[aria-label]'), 'data-desktop-new-session')
    const collapsed = frame.hasAttribute('data-sidebar-collapsed')
    for (const control of controls) {
      const source = sidebar.querySelector(control.selector)
      const svg = source?.querySelector(':scope > svg') || source?.querySelector('svg')
      if (svg && control.icon !== svg.outerHTML) {
        control.icon = svg.outerHTML
        control.button.replaceChildren(svg.cloneNode(true))
      }
      for (const name of ['aria-label', 'aria-keyshortcuts']) {
        const value = source?.getAttribute(name)
        if (value !== control.button.getAttribute(name)) {
          if (value === null || value === undefined) control.button.removeAttribute(name)
          else control.button.setAttribute(name, value)
        }
      }
      control.button.title = source?.getAttribute('aria-label') || ''
      control.button.disabled = !source || source.disabled
    }
    if (!collapsed && leading.contains(document.activeElement)) sidebar.querySelector('[data-desktop-sidebar-toggle]')?.focus({ preventScroll: true })
    leading.hidden = !collapsed || !row
    const width = `${collapsed ? 0 : sidebar.getBoundingClientRect().width}px`
    if (root.style.getPropertyValue('--desktop-sidebar-width') !== width) root.style.setProperty('--desktop-sidebar-width', width)
    const columns = frame.style.gridTemplateColumns.replace(/^[\d.]+px/, '0px')
    if (frame.style.getPropertyValue('--desktop-collapsed-columns') !== columns) frame.style.setProperty('--desktop-collapsed-columns', columns)
  }
  const schedule = () => { if (!pending) { pending = true; requestAnimationFrame(update) } }
  new MutationObserver(schedule).observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ['data-sidebar-collapsed', 'style', 'aria-label'] })
  window.addEventListener('resize', schedule)
  schedule()
}

/** Windows 两个入口调用原生菜单，鼠标打开菜单时保留编辑器焦点。 */
function mountMenu() {
  const host = document.createElement('div')
  host.id = 'desktop-menu'
  const shadow = host.attachShadow({ mode: 'open' })
  const style = document.createElement('style')
  style.textContent = `
    :host { position:fixed; top:0; left:var(--dsh-windows-menu-start,48px); z-index:1100;
      height:var(--dsh-windows-titlebar-height); display:flex; align-items:center;
      -webkit-app-region:no-drag; font:14px "Segoe UI", "Microsoft YaHei", sans-serif; }
    [role=menubar] { display:flex; gap:2px; }
    button { border:0; border-radius:6px; background:transparent; color:var(--dsw-alias-label-secondary, var(--desktop-text));
      padding:0 10px; height:28px; font:inherit; }
    button:hover, button[aria-expanded=true] { background:var(--dsw-alias-interactive-bg-hover, #8883); }
    button:focus-visible { outline:2px solid #4d6bfe; outline-offset:-2px; }
  `
  const bar = document.createElement('div')
  bar.setAttribute('role', 'menubar')
  bar.setAttribute('aria-label', currentLanguage === 'en' ? 'App menu' : '应用菜单')
  let restoreEditor = () => {}
  document.addEventListener('focusout', event => {
    const editor = event.composedPath()[0]
    if (!(editor instanceof HTMLElement) || shadow.contains(editor)) return
    const input = editor instanceof HTMLInputElement || editor instanceof HTMLTextAreaElement
    if (!input && !editor.isContentEditable) return
    const selection = document.getSelection()
    const ranges = selection ? Array.from({ length: selection.rangeCount }, (_, i) => selection.getRangeAt(i).cloneRange()) : []
    const start = input ? editor.selectionStart : null, end = input ? editor.selectionEnd : null
    restoreEditor = () => {
      if (!editor.isConnected) return
      editor.focus({ preventScroll: true })
      if (input && start !== null && end !== null) editor.setSelectionRange(start, end)
      else if (selection && ranges.length) { selection.removeAllRanges(); for (const range of ranges) selection.addRange(range) }
    }
  }, true)
  const buttons = (currentLanguage === 'en' ? ['App', 'Edit'] : ['应用', '编辑']).map((label, index) => {
    const button = document.createElement('button')
    button.textContent = label
    button.type = 'button'
    button.setAttribute('role', 'menuitem')
    button.setAttribute('aria-haspopup', 'menu')
    button.setAttribute('aria-expanded', 'false')
    button.addEventListener('mousedown', event => event.preventDefault())
    const open = async () => {
      if (button.getAttribute('aria-expanded') === 'true') return
      const rect = button.getBoundingClientRect()
      button.setAttribute('aria-expanded', 'true')
      if (document.activeElement === host) restoreEditor()
      try { await ipcRenderer.invoke('desktop:chrome-menu', index ? 'edit' : 'application', rect.left, rect.bottom) }
      catch (error) { console.error('Menu failed to open:', error) }
      finally { button.setAttribute('aria-expanded', 'false') }
    }
    button.addEventListener('click', open)
    button.addEventListener('keydown', event => {
      if (['ArrowLeft', 'ArrowRight', 'ArrowDown'].includes(event.key)) {
        event.preventDefault()
        if (event.key === 'ArrowDown') void open()
        else buttons[1 - index].focus()
      }
    })
    bar.append(button)
    return button
  })
  window.addEventListener('desktop-menu-language', () => {
    bar.setAttribute('aria-label', currentLanguage === 'en' ? 'App menu' : '应用菜单')
    buttons.forEach((button, i) => { button.textContent = (currentLanguage === 'en' ? ['App', 'Edit'] : ['应用', '编辑'])[i] })
  })
  shadow.append(style, bar)
  document.body.append(host)
}

/** 读取内核的实际主题 token，转成原生标题栏支持的 RGB。 */
function watchPalette() {
  const probe = document.createElement('span')
  probe.style.cssText = 'position:fixed;visibility:hidden;pointer-events:none;background:var(--dsw-specific-sidebar-fill);color:var(--dsw-alias-label-primary);border-color:var(--dsw-alias-bg-base)'
  document.body.append(probe)
  const context = document.createElement('canvas').getContext('2d', { willReadFrequently: true })
  let last = '', pending = false
  const hex = color => {
    context.clearRect(0, 0, 1, 1)
    context.fillStyle = color
    context.fillRect(0, 0, 1, 1)
    const rgb = context.getImageData(0, 0, 1, 1).data
    return '#' + Array.from(rgb).slice(0, 3).map(v => v.toString(16).padStart(2, '0')).join('')
  }
  const read = () => {
    pending = false
    if (!getComputedStyle(probe).getPropertyValue('--dsw-specific-sidebar-fill').trim()) return
    const computed = getComputedStyle(probe)
    const value = { sidebar: hex(computed.backgroundColor), content: hex(computed.borderTopColor), text: hex(computed.color),
      dark: document.body.hasAttribute('data-ds-dark-theme') || document.documentElement.hasAttribute('data-ds-dark-theme'),
      source: document.documentElement.dataset.dsThemeSource,
      language: document.documentElement.lang.toLowerCase().startsWith('zh') ? 'zh' : 'en' }
    const next = JSON.stringify(value)
    if (next !== last) { last = next; ipcRenderer.send('desktop:chrome-palette', value) }
  }
  const schedule = () => { if (!pending) { pending = true; queueMicrotask(read) } }
  const observer = new MutationObserver(schedule)
  observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class', 'style', 'data-ds-dark-theme', 'data-ds-theme-source', 'lang'] })
  observer.observe(document.body, { attributes: true, attributeFilter: ['class', 'style', 'data-ds-dark-theme'] })
  observer.observe(document.head, { childList: true, subtree: true, characterData: true })
  matchMedia('(prefers-color-scheme: dark)').addEventListener('change', schedule)
  read()
}

if (initialState) {
  let state = initialState
  ipcRenderer.on('desktop:chrome-state', (_event, next) => {
    state = next
    if (document.documentElement) applyState(state)
    window.dispatchEvent(new Event('desktop-menu-language'))
  })
  window.addEventListener('resize', () => { applyState(state); ipcRenderer.send('desktop:chrome-resize') })
  window.addEventListener('DOMContentLoaded', () => {
    applyState(state)
    if ((state.local && state.platform !== 'linux') || state.platform === 'darwin') {
      const title = document.createElement('header')
      title.id = 'desktop-titlebar'
      title.textContent = state.purpose === 'settings' ? (currentLanguage === 'en' ? 'Configuration center' : '配置中心') : state.platform === 'darwin' ? '' : 'DeepSeek Harness'
      document.body.prepend(title)
    }
    if (!state.local) {
      if (state.platform === 'win32') mountMenu()
      if (state.platform === 'darwin') watchMacLayout()
      watchPalette()
    }
  }, { once: true })
}
